- hosts: web
  gather_facts: false

  vars: 
    region: ap-south-1
    instance_type: t2.micro
    ami: ami-05695932c5299858a
    keypair: Terraform
 
  tasks:
    - name: create an ec2 instance
      ec2:
         aws_access_key: ''
         aws_secret_key: ''
         key_name: "{{ keypair }}"
         group: mysg
         instance_type: "{{ instance_type }}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1
         vpc_subnet_id: "<idofsubnet>"
         assign_public_ip: yes
      register: ec2

