---
- hosts: dev
  become: yes
  gather_facts: false
  tasks:
    - name: Download jenkins war file
      get_url:
        url: https://updates.jenkins-ci.org/download/war/2.241/jenkins.war
        dest: /home/spovedd
        mode: '0777'
