---
- name: This is a simple play to understand debug module
  hosts: all
  tasks:
    - name: Printing a messsage with msg parameter of debug module
      debug:
        msg:
          - "Welcome to Ansible Playbooks"
          - "Hello to Ansible"
    - debug: msg="Welcome to ansible Playbooks"
